{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example",
    "module": "platform-project",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "zpm2atjz3nhsbfqjpqexcij6yi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "com.example",
          "module": "library-project",
          "version": {
            "requires": "1.0.0"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "com.example",
          "module": "library-project",
          "version": {
            "requires": "1.0.0"
          }
        }
      ]
    }
  ]
}
